/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/MustangMach.glb 
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';

export function MustangMach(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/MustangMach.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 1.575]} scale={0.004}>
        <mesh geometry={nodes.BodyMtl.geometry} material={materials.BaseMtl} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
        <mesh geometry={nodes.BodyMtl001.geometry} material={materials['Slaughter.001']} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
        <mesh geometry={nodes.BodyMtl002.geometry} material={materials.BatLady} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
        <mesh geometry={nodes.BodyMtl003.geometry} material={materials.BrakeLine} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
        <mesh geometry={nodes.BodyMtl004.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
        <mesh geometry={nodes.BodyMtl005.geometry} material={materials.Embers} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
        <mesh geometry={nodes.BodyMtl006.geometry} material={materials['SpiderID.001']} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
        <mesh geometry={nodes.BodyMtl007.geometry} material={materials.Fluid} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
        <mesh geometry={nodes.BodyMtl008.geometry} material={materials.HotRods} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
        <mesh geometry={nodes.BodyMtl009.geometry} material={materials['Mayan.001']} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
        <mesh geometry={nodes.BodyMtl010.geometry} material={materials['SeaBreeze.001']} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
        <mesh geometry={nodes.BodyMtl011.geometry} material={materials['ShapeShifter.001']} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
        <mesh geometry={nodes.BodyMtl012.geometry} material={materials['Silk.001']} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
        <mesh geometry={nodes.BodyMtl013.geometry} material={materials['SnakeSkin.001']} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
        <mesh geometry={nodes.BodyMtl014.geometry} material={materials.Flare} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
        <mesh geometry={nodes.BodyMtl015.geometry} material={materials.Dominator} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
        <mesh geometry={nodes.BodyMtl016.geometry} material={materials['TopGun ']} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
        <mesh geometry={nodes.BodyMtl017.geometry} material={materials.Explosion} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
        <mesh geometry={nodes.BodyMtl018.geometry} material={materials['WildWest.001']} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
        <mesh geometry={nodes.BodyMtl019.geometry} material={materials['Zombie.001']} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
        <mesh geometry={nodes.Object_10.geometry} material={materials.Red_Light} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_2.geometry} material={materials['04___Default']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Red_Light} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.black_refl} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.brake} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.brake} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.brake} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.brake} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.brake} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.brake} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.brake} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.brake} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['07___Default777']} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.orange_light} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.red111} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.toyo} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Iron_Clean_Distorted} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Red_Light} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/MustangMach.glb')
